# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: corepb.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 5, "", "corepb.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63orepb.proto\x12\x06\x63orepb"i\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x12\x13\n\x0b\x65xpire_time\x18\x03 \x01(\x03\x12\x0b\n\x03uid\x18\x06 \x01(\x03\x12\x0e\n\x06is_new\x18\x07 \x01(\x08\x12\x14\n\x0cmutant_types\x18\x08 \x03(\x03"&\n\x07ItemBag\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Item"4\n\x07ItemChg\x12\x1a\n\x04item\x18\x01 \x01(\x0b\x32\x0c.corepb.Item\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "corepb_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ITEM"]._serialized_start = 24
    _globals["_ITEM"]._serialized_end = 129
    _globals["_ITEMBAG"]._serialized_start = 131
    _globals["_ITEMBAG"]._serialized_end = 169
    _globals["_ITEMCHG"]._serialized_start = 171
    _globals["_ITEMCHG"]._serialized_end = 223
# @@protoc_insertion_point(module_scope)
