# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 5, "", "game.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ngame.proto\x12\x06gatepb"\xf9\x01\n\x04Meta\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0bmethod_name\x18\x02 \x01(\t\x12\x14\n\x0cmessage_type\x18\x03 \x01(\x05\x12\x12\n\nclient_seq\x18\x04 \x01(\x03\x12\x12\n\nserver_seq\x18\x05 \x01(\x03\x12\x12\n\nerror_code\x18\x06 \x01(\x03\x12\x15\n\rerror_message\x18\x07 \x01(\t\x12,\n\x08metadata\x18\x08 \x03(\x0b\x32\x1a.gatepb.Meta.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01"3\n\x07Message\x12\x1a\n\x04meta\x18\x01 \x01(\x0b\x32\x0c.gatepb.Meta\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c"2\n\x0c\x45ventMessage\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c"7\n\rKickoutNotify\x12\x0e\n\x06reason\x18\x01 \x01(\x03\x12\x16\n\x0ereason_message\x18\x02 \x01(\t*>\n\x0bMessageType\x12\x08\n\x04None\x10\x00\x12\x0b\n\x07Request\x10\x01\x12\x0c\n\x08Response\x10\x02\x12\n\n\x06Notify\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "game_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_META_METADATAENTRY"]._loaded_options = None
    _globals["_META_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_MESSAGETYPE"]._serialized_start = 436
    _globals["_MESSAGETYPE"]._serialized_end = 498
    _globals["_META"]._serialized_start = 23
    _globals["_META"]._serialized_end = 272
    _globals["_META_METADATAENTRY"]._serialized_start = 225
    _globals["_META_METADATAENTRY"]._serialized_end = 272
    _globals["_MESSAGE"]._serialized_start = 274
    _globals["_MESSAGE"]._serialized_end = 325
    _globals["_EVENTMESSAGE"]._serialized_start = 327
    _globals["_EVENTMESSAGE"]._serialized_end = 377
    _globals["_KICKOUTNOTIFY"]._serialized_start = 379
    _globals["_KICKOUTNOTIFY"]._serialized_end = 434
# @@protoc_insertion_point(module_scope)
