# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: itempb.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 5, "", "itempb.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import corepb_pb2 as corepb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0citempb.proto\x12\rgamepb.itempb\x1a\x0c\x63orepb.proto"\x0c\n\nBagRequest"-\n\x08\x42\x61gReply\x12!\n\x08item_bag\x18\x01 \x01(\x0b\x32\x0f.corepb.ItemBag"*\n\x0bSellRequest\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Item"N\n\tSellReply\x12 \n\nsell_items\x18\x01 \x03(\x0b\x32\x0c.corepb.Item\x12\x1f\n\tget_items\x18\x02 \x03(\x0b\x32\x0c.corepb.Item">\n\nUseRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x12\x10\n\x08land_ids\x18\x03 \x03(\x03"\'\n\x08UseReply\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Item")\n\x07UseItem\x12\x0f\n\x07item_id\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x03"8\n\x0f\x42\x61tchUseRequest\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.gamepb.itempb.UseItem",\n\rBatchUseReply\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.corepb.Itemb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "itempb_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BAGREQUEST"]._serialized_start = 45
    _globals["_BAGREQUEST"]._serialized_end = 57
    _globals["_BAGREPLY"]._serialized_start = 59
    _globals["_BAGREPLY"]._serialized_end = 104
    _globals["_SELLREQUEST"]._serialized_start = 106
    _globals["_SELLREQUEST"]._serialized_end = 148
    _globals["_SELLREPLY"]._serialized_start = 150
    _globals["_SELLREPLY"]._serialized_end = 228
    _globals["_USEREQUEST"]._serialized_start = 230
    _globals["_USEREQUEST"]._serialized_end = 292
    _globals["_USEREPLY"]._serialized_start = 294
    _globals["_USEREPLY"]._serialized_end = 333
    _globals["_USEITEM"]._serialized_start = 335
    _globals["_USEITEM"]._serialized_end = 376
    _globals["_BATCHUSEREQUEST"]._serialized_start = 378
    _globals["_BATCHUSEREQUEST"]._serialized_end = 434
    _globals["_BATCHUSEREPLY"]._serialized_start = 436
    _globals["_BATCHUSEREPLY"]._serialized_end = 480
# @@protoc_insertion_point(module_scope)
