# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shoppb.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 5, "", "shoppb.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import corepb_pb2 as corepb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cshoppb.proto\x12\rgamepb.shoppb\x1a\x0c\x63orepb.proto"D\n\x0bShopProfile\x12\x0f\n\x07shop_id\x18\x01 \x01(\x03\x12\x11\n\tshop_name\x18\x02 \x01(\t\x12\x11\n\tshop_type\x18\x03 \x01(\x05"\xaa\x01\n\tGoodsInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nbought_num\x18\x02 \x01(\x03\x12\r\n\x05price\x18\x03 \x01(\x03\x12\x13\n\x0blimit_count\x18\x04 \x01(\x03\x12\x10\n\x08unlocked\x18\x05 \x01(\x08\x12\x0f\n\x07item_id\x18\x06 \x01(\x03\x12\x12\n\nitem_count\x18\x07 \x01(\x03\x12"\n\x05\x63onds\x18\x08 \x03(\x0b\x32\x13.gamepb.shoppb.Cond"#\n\x04\x43ond\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\x03"\x15\n\x13ShopProfilesRequest"F\n\x11ShopProfilesReply\x12\x31\n\rshop_profiles\x18\x01 \x03(\x0b\x32\x1a.gamepb.shoppb.ShopProfile""\n\x0fShopInfoRequest\x12\x0f\n\x07shop_id\x18\x01 \x01(\x03"=\n\rShopInfoReply\x12,\n\ngoods_list\x18\x01 \x03(\x0b\x32\x18.gamepb.shoppb.GoodsInfo"?\n\x0f\x42uyGoodsRequest\x12\x10\n\x08goods_id\x18\x01 \x01(\x03\x12\x0b\n\x03num\x18\x02 \x01(\x03\x12\r\n\x05price\x18\x03 \x01(\x03"{\n\rBuyGoodsReply\x12\'\n\x05goods\x18\x01 \x01(\x0b\x32\x18.gamepb.shoppb.GoodsInfo\x12\x1f\n\tget_items\x18\x02 \x03(\x0b\x32\x0c.corepb.Item\x12 \n\ncost_items\x18\x03 \x03(\x0b\x32\x0c.corepb.Item"A\n\x11GoodsUnlockNotify\x12,\n\ngoods_list\x18\x01 \x03(\x0b\x32\x18.gamepb.shoppb.GoodsInfo*A\n\x08\x43ondType\x12\x15\n\x11\x43OND_TYPE_UNKNOWN\x10\x00\x12\r\n\tMIN_LEVEL\x10\x01\x12\x0f\n\x0bUNLOCK_CARD\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "shoppb_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CONDTYPE"]._serialized_start = 776
    _globals["_CONDTYPE"]._serialized_end = 841
    _globals["_SHOPPROFILE"]._serialized_start = 45
    _globals["_SHOPPROFILE"]._serialized_end = 113
    _globals["_GOODSINFO"]._serialized_start = 116
    _globals["_GOODSINFO"]._serialized_end = 286
    _globals["_COND"]._serialized_start = 288
    _globals["_COND"]._serialized_end = 323
    _globals["_SHOPPROFILESREQUEST"]._serialized_start = 325
    _globals["_SHOPPROFILESREQUEST"]._serialized_end = 346
    _globals["_SHOPPROFILESREPLY"]._serialized_start = 348
    _globals["_SHOPPROFILESREPLY"]._serialized_end = 418
    _globals["_SHOPINFOREQUEST"]._serialized_start = 420
    _globals["_SHOPINFOREQUEST"]._serialized_end = 454
    _globals["_SHOPINFOREPLY"]._serialized_start = 456
    _globals["_SHOPINFOREPLY"]._serialized_end = 517
    _globals["_BUYGOODSREQUEST"]._serialized_start = 519
    _globals["_BUYGOODSREQUEST"]._serialized_end = 582
    _globals["_BUYGOODSREPLY"]._serialized_start = 584
    _globals["_BUYGOODSREPLY"]._serialized_end = 707
    _globals["_GOODSUNLOCKNOTIFY"]._serialized_start = 709
    _globals["_GOODSUNLOCKNOTIFY"]._serialized_end = 774
# @@protoc_insertion_point(module_scope)
