# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: visitpb.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 5, "", "visitpb.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import plantpb_pb2 as plantpb__pb2
from . import userpb_pb2 as userpb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rvisitpb.proto\x12\x0egamepb.visitpb\x1a\rplantpb.proto\x1a\x0cuserpb.proto"0\n\x0c\x45nterRequest\x12\x10\n\x08host_gid\x18\x01 \x01(\x03\x12\x0e\n\x06reason\x18\x02 \x01(\x05"^\n\nEnterReply\x12\'\n\x05\x62\x61sic\x18\x01 \x01(\x0b\x32\x18.gamepb.userpb.BasicInfo\x12\'\n\x05lands\x18\x02 \x03(\x0b\x32\x18.gamepb.plantpb.LandInfo" \n\x0cLeaveRequest\x12\x10\n\x08host_gid\x18\x01 \x01(\x03"\x0c\n\nLeaveReply*t\n\x0b\x45nterReason\x12\x18\n\x14\x45NTER_REASON_UNKNOWN\x10\x00\x12\x17\n\x13\x45NTER_REASON_BUBBLE\x10\x01\x12\x17\n\x13\x45NTER_REASON_FRIEND\x10\x02\x12\x19\n\x15\x45NTER_REASON_INTERACT\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "visitpb_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ENTERREASON"]._serialized_start = 256
    _globals["_ENTERREASON"]._serialized_end = 372
    _globals["_ENTERREQUEST"]._serialized_start = 62
    _globals["_ENTERREQUEST"]._serialized_end = 110
    _globals["_ENTERREPLY"]._serialized_start = 112
    _globals["_ENTERREPLY"]._serialized_end = 206
    _globals["_LEAVEREQUEST"]._serialized_start = 208
    _globals["_LEAVEREQUEST"]._serialized_end = 240
    _globals["_LEAVEREPLY"]._serialized_start = 242
    _globals["_LEAVEREPLY"]._serialized_end = 254
# @@protoc_insertion_point(module_scope)
